skip_selection = false

[GTK]
application_prefer_dark_theme = true
cursor_theme_name = "Adwaita"
cursor_blink = true
font_name = "JetBrainsMono Nerd Font 11"
icon_theme_name = "Adwaita"
theme_name = "Adwaita"

[commands]
reboot = ["systemctl", "reboot"]
poweroff = ["systemctl", "poweroff"]

[appearance]
greeting_msg = "Welcome back"

[widget.clock]
format = "%a  %H:%M"
resolution = "1s"
label_width = 150
